name: Run Discord Bot

on:
  schedule:
    - cron: "0 12 * * 6"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Create Tech Session Thread
        run: |
          thread_name=":thread: Topic $(date -d '+7 days' +'%Y-%m-%d')"
          response=$(curl -s -w "\n%{http_code}" -H "Authorization: Bot ${{ secrets.TECH_SESSION_THREAD_BOT_TOKEN }}" \
                           -H "Content-Type: application/json" \
                           -X POST \
                           -d '{
                                 "name": "'"${thread_name}"'",
                                 "type": 10,
                                 "auto_archive_duration": 10080
                               }' \
                           https://discord.com/api/v10/channels/${{ secrets.DISCORD_CHANNEL_ID_TECH_SESSION }}/threads)
          http_body=$(echo "$response" | sed '$d')
          http_code=$(echo "$response" | tail -n1)
          echo "HTTP Response Body: $http_body"
          echo "HTTP Response Code: $http_code"
          if [ "$http_code" -ne 200 ] && [ "$http_code" -ne 201 ]; then
            echo "Failed to create thread. HTTP Response Code: $http_code"
            exit 1
          fi
          echo "Successfully created thread: $http_body"
